import type { FilterOption, Product } from "./types";

export const PURPOSES: FilterOption[] = [
  { slug: "immunity", label: "Иммунитет" },
  { slug: "vitamins-minerals", label: "Витамины и минералы" },
  { slug: "gut-health", label: "ЖКТ и пищеварение" },
  { slug: "sleep-nervous", label: "Сон и нервная система" },
  { slug: "sport-energy", label: "Спорт и энергия" },
  { slug: "joints-bones", label: "Суставы и кости" },
  { slug: "beauty-skin", label: "Красота и кожа" },
  { slug: "heart-vessels", label: "Сердце и сосуды" },
  { slug: "detox-liver", label: "Детокс и печень" },
  { slug: "womens-health", label: "Женское здоровье" },
  { slug: "mens-health", label: "Мужское здоровье" },
  { slug: "eyesight", label: "Зрение" },
  { slug: "anti-age", label: "Anti-age и долголетие" },
  { slug: "kids-health", label: "Детское здоровье" },
];

export const ACTIVE_COMPONENTS: FilterOption[] = [
  { slug: "vitamin-d", label: "Витамин D" },
  { slug: "vitamin-c", label: "Витамин C" },
  { slug: "vitamin-b", label: "Витамин B" },
  { slug: "magnesium", label: "Магний" },
  { slug: "zinc", label: "Цинк" },
  { slug: "iron", label: "Железо" },
  { slug: "omega-3", label: "Омега-3" },
  { slug: "collagen", label: "Коллаген" },
  { slug: "probiotics", label: "Пробиотики" },
  { slug: "melatonin", label: "Мелатонин" },
  { slug: "coq10", label: "Коэнзим Q10" },
  { slug: "curcumin", label: "Куркумин" },
  { slug: "ashwagandha", label: "Ашваганда" },
  { slug: "calcium", label: "Кальций" },
  { slug: "iodine", label: "Йод" },
  { slug: "fiber", label: "Клетчатка" },
];

export const FORM_LABELS: Record<Product["form"], string> = {
  capsules: "Капсулы",
  tablets: "Таблетки",
  powder: "Порошок",
  liquid: "Жидкость",
  gummies: "Пастилки",
};

export const PRODUCTS: Product[] = [
  {
    id: "p01",
    slug: "vitamin-d3-2000",
    name: "Витамин D3 2000 МЕ",
    brand: "NutriHome Basics",
    price: 590,
    ageGroup: "adult",
    purposes: ["immunity", "vitamins-minerals", "anti-age"],
    activeComponents: ["vitamin-d"],
    form: "capsules",
    volume: "60 капсул",
    description: "Поддержка иммунитета, костей и настроения в тёмное время года.",
    rating: 4.8,
    reviewsCount: 214,
    inStock: true,
    isHit: true,
    accent: "brand",
  },
  {
    id: "p02",
    slug: "magnesium-b6-chelate",
    name: "Магний B6 хелат",
    brand: "VitaLab",
    price: 780,
    ageGroup: "adult",
    purposes: ["sleep-nervous", "sport-energy"],
    activeComponents: ["magnesium", "vitamin-b"],
    form: "capsules",
    volume: "90 капсул",
    description: "Лёгкая усвояемая форма магния для сна, мышц и нервной системы.",
    rating: 4.7,
    reviewsCount: 188,
    inStock: true,
    accent: "leaf",
  },
  {
    id: "p03",
    slug: "omega-3-1000",
    name: "Омега-3 рыбий жир 1000 мг",
    brand: "OceanWell",
    price: 1450,
    oldPrice: 1750,
    ageGroup: "adult",
    purposes: ["heart-vessels", "eyesight", "anti-age"],
    activeComponents: ["omega-3"],
    form: "capsules",
    volume: "90 капсул",
    description: "Высокая концентрация EPA/DHA для сердца, сосудов и зрения.",
    rating: 4.9,
    reviewsCount: 341,
    inStock: true,
    isHit: true,
    accent: "brand",
  },
  {
    id: "p04",
    slug: "zinc-picolinate-25",
    name: "Цинк пиколинат 25 мг",
    brand: "NutriHome Basics",
    price: 520,
    ageGroup: "adult",
    purposes: ["immunity", "beauty-skin", "mens-health"],
    activeComponents: ["zinc"],
    form: "capsules",
    volume: "60 капсул",
    description: "Легкоусвояемый цинк для иммунитета, кожи и гормонального баланса.",
    rating: 4.6,
    reviewsCount: 152,
    inStock: true,
    accent: "amber",
  },
  {
    id: "p05",
    slug: "probiotic-10-strains",
    name: "Пробиотик 10 штаммов",
    brand: "BioBalance",
    price: 1290,
    ageGroup: "adult",
    purposes: ["gut-health", "immunity"],
    activeComponents: ["probiotics"],
    form: "capsules",
    volume: "30 капсул",
    description: "10 штаммов бактерий и 20 млрд КОЕ для баланса микрофлоры.",
    rating: 4.7,
    reviewsCount: 97,
    inStock: true,
    accent: "leaf",
  },
  {
    id: "p06",
    slug: "marine-collagen-vitc",
    name: "Коллаген морской + витамин C",
    brand: "PureForm",
    price: 1990,
    ageGroup: "adult",
    purposes: ["beauty-skin", "joints-bones"],
    activeComponents: ["collagen", "vitamin-c"],
    form: "powder",
    volume: "200 г",
    description: "Гидролизованный морской коллаген для кожи, волос и суставов.",
    rating: 4.8,
    reviewsCount: 263,
    inStock: true,
    isHit: true,
    accent: "berry",
  },
  {
    id: "p07",
    slug: "multivitamin-women",
    name: "Мультивитамины для женщин",
    brand: "VitaLab",
    price: 890,
    ageGroup: "adult",
    purposes: ["womens-health", "vitamins-minerals", "beauty-skin"],
    activeComponents: ["iron", "vitamin-b"],
    form: "tablets",
    volume: "30 таблеток",
    description: "22 витамина и минерала, подобранных для женского организма.",
    rating: 4.6,
    reviewsCount: 176,
    inStock: true,
    accent: "berry",
  },
  {
    id: "p08",
    slug: "multivitamin-men",
    name: "Мультивитамины для мужчин",
    brand: "VitaLab",
    price: 890,
    ageGroup: "adult",
    purposes: ["mens-health", "sport-energy", "vitamins-minerals"],
    activeComponents: ["zinc", "vitamin-b"],
    form: "tablets",
    volume: "30 таблеток",
    description: "Комплекс для энергии, тонуса и мужского здоровья.",
    rating: 4.5,
    reviewsCount: 141,
    inStock: true,
    accent: "brand",
  },
  {
    id: "p09",
    slug: "kids-vitamin-bears",
    name: "Витаминки-мишки для детей",
    brand: "Kids Harmony",
    price: 690,
    ageGroup: "kids",
    purposes: ["kids-health", "immunity"],
    activeComponents: ["vitamin-c"],
    form: "gummies",
    volume: "60 пастилок",
    description: "Вкусные жевательные мишки с витамином C для крепкого иммунитета.",
    rating: 4.9,
    reviewsCount: 302,
    inStock: true,
    isHit: true,
    accent: "berry",
  },
  {
    id: "p10",
    slug: "iron-chelate-25",
    name: "Железо хелат 25 мг",
    brand: "NutriHome Basics",
    price: 640,
    ageGroup: "adult",
    purposes: ["womens-health", "vitamins-minerals"],
    activeComponents: ["iron"],
    form: "capsules",
    volume: "60 капсул",
    description: "Бережная форма железа без раздражения ЖКТ.",
    rating: 4.5,
    reviewsCount: 88,
    inStock: true,
    accent: "amber",
  },
  {
    id: "p11",
    slug: "vitamin-c-1000",
    name: "Витамин C 1000 мг",
    brand: "PureForm",
    price: 450,
    oldPrice: 590,
    ageGroup: "adult",
    purposes: ["immunity"],
    activeComponents: ["vitamin-c"],
    form: "tablets",
    volume: "90 таблеток",
    description: "Классика для сезонной поддержки иммунитета.",
    rating: 4.7,
    reviewsCount: 256,
    inStock: true,
    accent: "amber",
  },
  {
    id: "p12",
    slug: "valerian-extract",
    name: "Валериана экстракт",
    brand: "HerbaCore",
    price: 380,
    ageGroup: "adult",
    purposes: ["sleep-nervous"],
    activeComponents: [],
    form: "capsules",
    volume: "60 капсул",
    description: "Мягкое растительное средство для спокойствия и сна.",
    rating: 4.4,
    reviewsCount: 64,
    inStock: true,
    accent: "leaf",
  },
  {
    id: "p13",
    slug: "melatonin-3",
    name: "Мелатонин 3 мг",
    brand: "VitaLab",
    price: 560,
    ageGroup: "adult",
    purposes: ["sleep-nervous"],
    activeComponents: ["melatonin"],
    form: "capsules",
    volume: "30 капсул",
    description: "Помогает быстрее засыпать и адаптироваться при смене часовых поясов.",
    rating: 4.6,
    reviewsCount: 129,
    inStock: true,
    accent: "brand",
  },
  {
    id: "p14",
    slug: "curcumin-piperine",
    name: "Куркумин с пиперином",
    brand: "GreenLeaf Naturals",
    price: 1190,
    ageGroup: "adult",
    purposes: ["joints-bones", "detox-liver", "anti-age"],
    activeComponents: ["curcumin"],
    form: "capsules",
    volume: "60 капсул",
    description: "Куркумин с усилителем усвоения для суставов и печени.",
    rating: 4.6,
    reviewsCount: 103,
    inStock: true,
    accent: "amber",
  },
  {
    id: "p15",
    slug: "ashwagandha-ksm66",
    name: "Ашваганда KSM-66",
    brand: "GreenLeaf Naturals",
    price: 990,
    ageGroup: "adult",
    purposes: ["sleep-nervous", "sport-energy", "anti-age"],
    activeComponents: ["ashwagandha"],
    form: "capsules",
    volume: "60 капсул",
    description: "Адаптоген для устойчивости к стрессу и восстановления.",
    rating: 4.8,
    reviewsCount: 178,
    inStock: true,
    isHit: true,
    accent: "leaf",
  },
  {
    id: "p16",
    slug: "spirulina-500",
    name: "Спирулина 500 мг",
    brand: "GreenLeaf Naturals",
    price: 420,
    ageGroup: "adult",
    purposes: ["detox-liver", "vitamins-minerals"],
    activeComponents: [],
    form: "tablets",
    volume: "100 таблеток",
    description: "Природный источник белка, витаминов и хлорофилла.",
    rating: 4.3,
    reviewsCount: 51,
    inStock: true,
    accent: "leaf",
  },
  {
    id: "p17",
    slug: "psyllium-fiber",
    name: "Клетчатка псиллиум",
    brand: "BioBalance",
    price: 480,
    ageGroup: "adult",
    purposes: ["gut-health", "detox-liver"],
    activeComponents: ["fiber"],
    form: "powder",
    volume: "250 г",
    description: "Растворимая клетчатка для мягкого пищеварения.",
    rating: 4.5,
    reviewsCount: 72,
    inStock: true,
    accent: "leaf",
  },
  {
    id: "p18",
    slug: "hyaluronic-acid",
    name: "Гиалуроновая кислота",
    brand: "PureForm",
    price: 1350,
    ageGroup: "adult",
    purposes: ["beauty-skin", "joints-bones"],
    activeComponents: [],
    form: "capsules",
    volume: "30 капсул",
    description: "Увлажнение кожи и поддержка суставов изнутри.",
    rating: 4.6,
    reviewsCount: 94,
    inStock: true,
    accent: "berry",
  },
  {
    id: "p19",
    slug: "l-carnitine-500",
    name: "L-карнитин 500 мг",
    brand: "ActivePeak",
    price: 720,
    ageGroup: "adult",
    purposes: ["sport-energy"],
    activeComponents: [],
    form: "capsules",
    volume: "90 капсул",
    description: "Поддержка энергообмена при тренировках.",
    rating: 4.4,
    reviewsCount: 66,
    inStock: true,
    accent: "amber",
  },
  {
    id: "p20",
    slug: "bcaa-2-1-1",
    name: "BCAA 2:1:1",
    brand: "ActivePeak",
    price: 1590,
    ageGroup: "adult",
    purposes: ["sport-energy"],
    activeComponents: [],
    form: "powder",
    volume: "300 г",
    description: "Аминокислоты для восстановления мышц после нагрузок.",
    rating: 4.5,
    reviewsCount: 112,
    inStock: true,
    accent: "amber",
  },
  {
    id: "p21",
    slug: "electrolytes-sport",
    name: "Электролиты спорт",
    brand: "ActivePeak",
    price: 890,
    oldPrice: 1050,
    ageGroup: "adult",
    purposes: ["sport-energy"],
    activeComponents: [],
    form: "powder",
    volume: "15 стиков",
    description: "Баланс солей и жидкости при активных тренировках.",
    rating: 4.6,
    reviewsCount: 58,
    inStock: true,
    accent: "amber",
  },
  {
    id: "p22",
    slug: "glucosamine-chondroitin",
    name: "Глюкозамин + Хондроитин",
    brand: "GreenLeaf Naturals",
    price: 1290,
    ageGroup: "adult",
    purposes: ["joints-bones"],
    activeComponents: [],
    form: "tablets",
    volume: "60 таблеток",
    description: "Комплекс для подвижности и здоровья суставов.",
    rating: 4.5,
    reviewsCount: 84,
    inStock: true,
    accent: "brand",
  },
  {
    id: "p23",
    slug: "soy-lecithin",
    name: "Лецитин соевый",
    brand: "NutriHome Basics",
    price: 460,
    ageGroup: "adult",
    purposes: ["heart-vessels", "anti-age"],
    activeComponents: [],
    form: "capsules",
    volume: "90 капсул",
    description: "Поддержка печени, памяти и обмена жиров.",
    rating: 4.3,
    reviewsCount: 39,
    inStock: true,
    accent: "brand",
  },
  {
    id: "p24",
    slug: "organic-iodine",
    name: "Йод органический",
    brand: "NutriHome Basics",
    price: 390,
    ageGroup: "adult",
    purposes: ["womens-health", "vitamins-minerals"],
    activeComponents: ["iodine"],
    form: "capsules",
    volume: "60 капсул",
    description: "Поддержка щитовидной железы и обмена веществ.",
    rating: 4.4,
    reviewsCount: 47,
    inStock: true,
    accent: "brand",
  },
  {
    id: "p25",
    slug: "selenium-vitamin-e",
    name: "Селен + витамин E",
    brand: "NutriHome Basics",
    price: 410,
    ageGroup: "adult",
    purposes: ["immunity", "anti-age"],
    activeComponents: [],
    form: "capsules",
    volume: "60 капсул",
    description: "Антиоксидантная пара для клеточной защиты.",
    rating: 4.4,
    reviewsCount: 53,
    inStock: true,
    accent: "amber",
  },
  {
    id: "p26",
    slug: "biotin-5000",
    name: "Биотин 5000 мкг",
    brand: "PureForm",
    price: 530,
    ageGroup: "adult",
    purposes: ["beauty-skin"],
    activeComponents: [],
    form: "capsules",
    volume: "60 капсул",
    description: "Для крепких волос, ногтей и здоровой кожи.",
    rating: 4.7,
    reviewsCount: 198,
    inStock: true,
    isHit: true,
    accent: "berry",
  },
  {
    id: "p27",
    slug: "folic-acid",
    name: "Фолиевая кислота",
    brand: "VitaLab",
    price: 280,
    ageGroup: "adult",
    purposes: ["womens-health"],
    activeComponents: [],
    form: "tablets",
    volume: "90 таблеток",
    description: "Важна на этапе планирования и в первом триместре.",
    rating: 4.6,
    reviewsCount: 71,
    inStock: true,
    accent: "berry",
  },
  {
    id: "p28",
    slug: "inulin-prebiotic",
    name: "Пребиотик инулин",
    brand: "BioBalance",
    price: 450,
    ageGroup: "adult",
    purposes: ["gut-health"],
    activeComponents: ["fiber"],
    form: "powder",
    volume: "200 г",
    description: "Питание для полезной микрофлоры кишечника.",
    rating: 4.3,
    reviewsCount: 34,
    inStock: true,
    accent: "leaf",
  },
  {
    id: "p29",
    slug: "ginkgo-biloba",
    name: "Гинкго билоба",
    brand: "HerbaCore",
    price: 610,
    ageGroup: "adult",
    purposes: ["anti-age", "eyesight"],
    activeComponents: [],
    form: "capsules",
    volume: "60 капсул",
    description: "Поддержка памяти, концентрации и микроциркуляции.",
    rating: 4.4,
    reviewsCount: 46,
    inStock: true,
    accent: "leaf",
  },
  {
    id: "p30",
    slug: "echinacea-purple",
    name: "Эхинацея пурпурная",
    brand: "HerbaCore",
    price: 470,
    oldPrice: 590,
    ageGroup: "adult",
    purposes: ["immunity"],
    activeComponents: [],
    form: "capsules",
    volume: "60 капсул",
    description: "Растительная поддержка иммунитета в сезон простуд.",
    rating: 4.5,
    reviewsCount: 89,
    inStock: true,
    accent: "leaf",
  },
  {
    id: "p31",
    slug: "milk-thistle-detox",
    name: "Расторопша (детокс печени)",
    brand: "HerbaCore",
    price: 420,
    ageGroup: "adult",
    purposes: ["detox-liver"],
    activeComponents: [],
    form: "capsules",
    volume: "60 капсул",
    description: "Классическая поддержка печени силимарином.",
    rating: 4.4,
    reviewsCount: 55,
    inStock: true,
    accent: "leaf",
  },
  {
    id: "p32",
    slug: "coenzyme-q10-100",
    name: "Коэнзим Q10 100 мг",
    brand: "OceanWell",
    price: 1690,
    ageGroup: "adult",
    purposes: ["heart-vessels", "anti-age"],
    activeComponents: ["coq10"],
    form: "capsules",
    volume: "30 капсул",
    description: "Энергия клеток и поддержка сердечно-сосудистой системы.",
    rating: 4.7,
    reviewsCount: 121,
    inStock: true,
    accent: "brand",
  },
  {
    id: "p33",
    slug: "vitamin-k2-d3",
    name: "Витамин K2 + D3",
    brand: "VitaLab",
    price: 890,
    ageGroup: "adult",
    purposes: ["joints-bones", "heart-vessels"],
    activeComponents: ["vitamin-d"],
    form: "capsules",
    volume: "60 капсул",
    description: "Тандем витаминов для крепких костей и здоровых сосудов.",
    rating: 4.8,
    reviewsCount: 167,
    inStock: true,
    isHit: true,
    accent: "brand",
  },
  {
    id: "p34",
    slug: "calcium-vitamin-d3",
    name: "Кальций + витамин D3",
    brand: "NutriHome Basics",
    price: 520,
    ageGroup: "adult",
    purposes: ["joints-bones", "kids-health"],
    activeComponents: ["calcium", "vitamin-d"],
    form: "tablets",
    volume: "90 таблеток",
    description: "Основа для крепких костей и зубов всей семьи.",
    rating: 4.5,
    reviewsCount: 98,
    inStock: true,
    accent: "brand",
  },
  {
    id: "p35",
    slug: "chromium-picolinate",
    name: "Пиколинат хрома",
    brand: "ActivePeak",
    price: 480,
    ageGroup: "adult",
    purposes: ["sport-energy", "vitamins-minerals"],
    activeComponents: [],
    form: "capsules",
    volume: "60 капсул",
    description: "Поддержка углеводного обмена и контроля аппетита.",
    rating: 4.2,
    reviewsCount: 29,
    inStock: false,
    accent: "amber",
  },
  {
    id: "p36",
    slug: "kids-fish-oil",
    name: "Рыбий жир для детей",
    brand: "Kids Harmony",
    price: 750,
    ageGroup: "kids",
    purposes: ["kids-health", "eyesight"],
    activeComponents: ["omega-3"],
    form: "gummies",
    volume: "60 пастилок",
    description: "Омега-3 в приятных пастилках для развития и зрения.",
    rating: 4.7,
    reviewsCount: 143,
    inStock: false,
    accent: "berry",
  },
  {
    id: "p37",
    slug: "red-ginseng-extract",
    name: "Женьшень красный экстракт",
    brand: "HerbaCore",
    price: 990,
    ageGroup: "adult",
    purposes: ["sport-energy", "mens-health", "anti-age"],
    activeComponents: [],
    form: "capsules",
    volume: "60 капсул",
    description: "Тонизирующее растительное средство для энергии и тонуса.",
    rating: 4.5,
    reviewsCount: 62,
    inStock: true,
    accent: "amber",
  },
  {
    id: "p38",
    slug: "kids-probiotic",
    name: "Пробиотик для детей",
    brand: "Kids Harmony",
    price: 890,
    ageGroup: "kids",
    purposes: ["kids-health", "gut-health"],
    activeComponents: ["probiotics"],
    form: "powder",
    volume: "30 саше",
    description: "Бережная формула для микрофлоры детского животика.",
    rating: 4.8,
    reviewsCount: 77,
    inStock: false,
    accent: "leaf",
  },
];

export const BRANDS: FilterOption[] = Array.from(
  new Set(PRODUCTS.map((product) => product.brand))
)
  .sort((a, b) => a.localeCompare(b, "ru"))
  .map((brand) => ({ slug: brand, label: brand }));

export const PRICE_BOUNDS = PRODUCTS.reduce(
  (bounds, product) => ({
    min: Math.min(bounds.min, product.price),
    max: Math.max(bounds.max, product.price),
  }),
  { min: Infinity, max: 0 }
);

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((product) => product.slug === slug);
}

export function getFeaturedProducts(limit = 8): Product[] {
  return PRODUCTS.filter((product) => product.isHit).slice(0, limit);
}
